---

- name: Install opendmarc support
  package:
    name: '{{ item }}'
    state: 'present'
  with_flattened:
    - '{{ opendmarc__base_packages }}'
    - '{{ opendmarc__packages }}'
  notify: [ 'Check opendmarc and restart' ]
  when: ansible_pkg_mgr == 'apt'

- name: Divert original opendmarc configuration
  command: dpkg-divert --quiet --local --divert /etc/opendmarc.conf.dpkg-divert --rename /etc/opendmarc.conf
  args:
    creates: '/etc/opendmarc.conf.dpkg-divert'
  when: ansible_pkg_mgr == 'apt'

- name: Make sure Ansible local facts directory exists
  file:
    dest: '/etc/ansible/facts.d'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: Configure opendmarc local facts
  template:
    src: 'etc/ansible/facts.d/opendmarc.fact.j2'
    dest: '/etc/ansible/facts.d/opendmarc.fact'
    owner: 'root'
    group: 'root'
    mode: '0755'
  register: opendmarc__register_facts

- name: Re-read local facts if they have been modified
  action: setup
  when: opendmarc__register_facts|changed

- name: Generate opendmarc configuration
  template:
    src: 'etc/opendmarc.conf.j2'
    dest: '/etc/opendmarc.conf'
    owner: 'root'
    group: '{{ opendmarc__group }}'
    mode: '0640'
  notify: [ 'Check opendmarc and reload' ]


- name: Create opendmarc socket directory in Postfix chroot
  file:
    path: '/var/spool/postfix/opendmarc'
    state: 'directory'
    owner: '{{ opendmarc__user }}'
    group: '{{ opendmarc__postfix_group }}'
    mode: '2750'
  when: opendmarc__postfix_integration|bool
  notify: [ 'Check opendmarc and restart' ]
