---

- name: Check opendmarc and restart
  command: opendmarc -n
  notify: [ 'Restart opendmarc' ]

- name: Check opendmarc and reload
  command: opendmarc -n
  notify: [ 'Reload opendmarc' ]
  when: ansible_local|d() and ansible_local.opendmarc|d() and
        ansible_local.opendmarc.installed is defined and
        ansible_local.opendmarc.installed | bool

- name: Restart opendmarc
  service:
    name: 'opendmarc'
    state: 'restarted'

- name: Reload opendmarc
  service:
    name: 'opendmarc'
    state: 'reloaded'
