---

- name: Manage opendmarc service
  hosts: [ 'debops_service_opendmarc' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:

    - role: debops.postfix/env
      tags: [ 'role::postfix', 'role::secret' ]
      when: opendmarc__postfix_integration|bool

    - role: debops.opendmarc/env
      tags: [ 'role::opendmarc', 'role::secret' ]

    - role: debops.secret
      tags: [ 'role::secret', 'role::opendmarc', 'role::postfix' ]
      secret__directories:
        - '{{ postfix__secret__directories  | d([]) }}'
        - '{{ opendmarc__secret__directories | d([]) }}'

    - role: debops.postfix
      tags: [ 'role::postfix' ]
      postfix__dependent_maincf:
        - role: 'opendmarc'
          config: '{{ opendmarc__postfix__dependent_maincf }}'
      when: opendmarc__postfix_integration|bool

    - role: debops.opendmarc
      tags: [ 'role::opendmarc' ]
